
on: ["workflow_dispatch", "publish"] #hm, is there a better one?

# available runs-on are listed here:
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: Build
jobs:
  build-ubuntu:
    name: Build-Ubuntu
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Setup Node.js 16.x
      uses: actions/setup-node@v2
      with:
        cache: yarn
        node-version: 16.x

    - name: Install and Test
      run: |
        yarn
        yarn build
  
  build-windows:
    name: Build-Windows
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@v3

    - name: Setup Node.js 16.x
      uses: actions/setup-node@v2
      with:
        cache: yarn
        node-version: 16.x

    - name: Install and Test
      run: |
        yarn
        yarn build
  
  build-osx:
    name: Build-OSX
    runs-on: osx-latest
    steps:

    - uses: actions/checkout@v3

    - name: Setup Node.js 16.x
      uses: actions/setup-node@v2
      with:
        cache: yarn
        node-version: 16.x

    - name: Install and Test
      run: |
        yarn
        yarn build
